title: "Memefluencer for Data Ethics"
author: "Paribartan Humagain,Natalia Scharfenberg,Niklas Bub"
description: "Study project Data Ethics Outreach Lab"
permalink: /:Memefluencer/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true            # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "browser.html"}
  - {file: "search_engine.html"}
  - {file: "messenger.html"}

external:    
  - {title: Github, icon: github, url: "https://github.com/pariyashu/data_ethics_outreach"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
